### ISSUE TITLE
Buying enough map crashes the game

### ISSUE THREAD

**Issue by SengulolanCem** [tobbetu-bil481-adarkroom/adarkroom#4]
## **Steps :**

1. Never have the scout show up for a long time.
2.Consequently, store up lots of fur and scales.
3.Have scout show up.
4.Learn scouting (finally!).
5.Buy map.
6.Repeat (5) ad infinitum.

## **Expected**

Be told when there are no more maps to buy.

## **Actual**

Browser tab hangs. It feels like maybe there is an infinite loop looking for more world to uncover? There are in fact a few tiny little pockets of uncovered world remaining.

https://github.com/doublespeakgames/adarkroom/issues/515

**Comment by cagdasgerede** [comment]
Bu bug'ı reproduce etmek ne kadar sürüyor? Anlatımdan sanki çok uzun bir zaman gibi geldi.
Demoda bug'ın ortadan kalktığını göstermek ne kadar sürecek?

**Comment by cagdasgerede** [comment]
?

**Comment by SengulolanCem** [comment]
Hocam 4-5 gündür issue için save game üretmeye çalışıyorum bunun içinde oyunda belli bir noktaya gelmek lazım. Issue sahibine de sordum kendisinde save game olmadığını söyledi. Biraz daha deneyip save game üretmeye çalışacağım eğer olmazsa issue değiştireceğim.
